Test that text input is entered after child window is closed
MirServer/wlcs pull request #216
Opened 2021-11-12 02:08 UTC by wmww

This is supposed to test https://github.com/MirServer/mir/issues/2189, but it passes for some reason. A problem for next week.

2021-11-15 23:49 UTC, wmww commented
Ah! I forgot to actually set the parent on the child. Fixed. (and by fixed, I mean the test is now failing as it should)

2021-11-16 02:29 UTC, wmww commented
https://github.com/MirServer/mir/pull/2223 fixes this test on Mir.

2022-03-18 00:48 UTC, RAOF requested changes
Oops! Looks like I left a review pending :grimacing: 

One non-blocking stylistic thing wrt `operator wl_surface*()`, one question about what we're testing that might require changes.

2022-03-18 13:42 UTC, wmww commented on tests/text_input_v3_with_input_method_v2.cpp
> +    EXPECT_CALL(text_input, enter(parent_surface->operator wl_surface*()));
I do believe some sort of explicit conversion is necessary. I, personally, like the explicit call to operator. Is there any reason to prefer static cast?

2022-03-18 13:53 UTC, wmww commented on tests/text_input_v3_with_input_method_v2.cpp
> +    EXPECT_CALL(text_input, enter(child_surface->operator wl_surface*())).Times(0);
Done

2022-11-15 14:24 UTC, AlanGriffiths commented on tests/text_input_v3_with_input_method_v2.cpp
> +    EXPECT_CALL(text_input, enter(parent_surface->operator wl_surface*()));
> I, personally, like the explicit call to operator.

I, personally, find it strange to invoke operators by calling the operator function by name. The point of such functions is that they can be invoked using operator syntax.

If the intended use is to call the function by name then there are better names.

I'd be tempted to introduce a helper function:

```c++
auto as_wl_surface(wlcs::Surface const& s) -> wl_surface*
{
    return s;
}
```
```suggestion
    EXPECT_CALL(text_input, enter(as_wl_surface((*parent_surface)));
```

2022-11-15 18:55 UTC, wmww commented on tests/text_input_v3_with_input_method_v2.cpp
> +    EXPECT_CALL(text_input, enter(parent_surface->operator wl_surface*()));
Is the latest update satisfactory?

2023-05-08 17:13 UTC, wmww commented
Ready for review

2023-05-15 07:53 UTC, RAOF approved these changes
A couple of nits, but this can land.

Feel free to fix them up, or not.

(I *think* the workflow for this now is just to approve and then let Sophie hit the “merge” button?)

2023-05-15 07:53 UTC, RAOF commented on tests/text_input_v3_with_input_method_v2.cpp
> +    EXPECT_CALL(text_input, enter(child_surface->wl_surface()));
Non-blocking, but this ordering is a protocol requirement, so we should probably enforce it.

2023-05-15 07:53 UTC, RAOF commented on tests/text_input_v3_with_input_method_v2.cpp
> +    auto child_xdg_toplevel = std::make_shared<wlcs::XdgPopupStable>(
Nit: `child_xdg_toplevel` -> `child_xdg_popup`

2023-05-15 08:10 UTC, Saviq commented
> (I _think_ the workflow for this now is just to approve and then let Sophie hit the “merge” button?)

Not before #289 :)

2023-05-15 17:34 UTC, merged